### PR TITLE
Build out CarrotU Overview based on Tech@Instacart Article

### PR DESCRIPTION
**Pull request by Robert-Border**
https://tech.instacart.com/carrot-u-building-an-in-house-coding-bootcamp-d2c0a746dd73

### Changelog
-Create partial to hold all CarrotU Overview html
-Add render in welcome.html.erb
-Update CSS for new classes specific to the CarrotU overview
-Update links in the Nav

### Checklist:
- [x] My code follows the style guideline
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Add tests if required
- [x] rake assets:precompile runs without issue

image

### UI Screenshots:
Updated homepage
image

image

image

### CODE REVIEW

**Comment by bradweee** [comment]
Looks good to me! Merge it!

**Comment by Robert-Border** [comment]
image


Made some updates on this last commit. Primarily aimed at reducing the length of the homepage and making it look more interesting.

**Comment by shaolinhoward** [comment]
> image
> 
> Made some updates on this last commit. Primarily aimed at reducing the length of the homepage and making it look more interesting.

🤩

**Comment by muffy** [comment]
Wow, that's gorgeous, thank you!

**Pull request merged**
