### PR TITLE
adding mentors controller, index view, and route

### PR DESCRIPTION
**Pull request by FrancieJ**
@viktor-evdokimov

### CODE REVIEW

**Comment by shaolinhoward** [comment]
Hey Francie - looks like some files have been updated in master, you'll need to rebase. Here is a article I dug up on rebasing: https://www.blog.duomly.com/git-rebase-tutorial-and-comparison-with-git-merge/

**Comment by FrancieJ** [comment]
@shaolinhoward I think I did the rebase but I'm not sure if it worked. Can you let me know please? Thanks!

**Comment by shaolinhoward** [comment]
Looks like there are still file conflicts (can't tell if they're new):
image
will need to rebase again

**Comment by shaolinhoward** [comment]
@FrancieJ - I've settled the merge conflicts and handled the rebase. Much of the changes were already in master so it reduced your branches changes quite a lot. If you have more changes then you can do `git pull` to grab the rebased branch otherwise it may make sense to close

**Pull request merged**
